version: "3"
services:
  ivs:
    build: ../..
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - postgres_test
      - redis
      - influxdb
    environment:
      - GIN_MODE=release
      - OC_DB_URL=host=postgres port=5432 user=lynxi password=lynxi dbname=ivs sslmode=disable
      - OC_NATS_URL=nats://nats:4222
      - OC_REDIS_URL=redis:6379
      - OC_LOGGER_URL=localhost:12201
      - OC_FILES_UPLOAD_URL=https://192.168.8.75:4000/files
      - OC_INFLUXDB_URL=http://influxdb:8086
    volumes:
      - ./server.crt:/server.crt
      - ./server.key:/server.key

  debug-proxy-test:
    image: alpine/socat
    depends_on:
      - postgres_test
      - redis
      - influxdb
      - chronograf
    ports:
      - "5433:5432"
      - "6380:6379"

    entrypoint: /bin/sh
    volumes:
      - ./debug-proxy.sh:/debug-proxy.sh
    command: /debug-proxy.sh

  postgres_test:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=pca
      - POSTGRES_USER=lynxi
      - POSTGRES_PASSWORD=lynxi

  redis:
    image: redis:alpine

#  nats:
#    image: nats-streaming:latest
#
#  live:
#    image: ossrs/srs:3.0.42
#    ports:
#      - "1935:1935"
#    volumes:
#      - ./realtime.conf:/srs/conf/realtime.conf
#    command: objs/srs -c /srs/conf/realtime.conf

  influxdb:
    image: influxdb:latest
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - ADMIN_USER="root"
      - INFLUXDB_INIT_PWD="root"
      - PRE_CREATE_DB="telegraf"
    volumes:
      - ./influxdb:/var/lib/influxdb

  chronograf:
    image: chronograf:latest
    command: chronograf --influxdb-url=http://influxdb:8086
